export const SHOP_CATEGORIES = {
  groceries: {
    name: "Groceries",
    categories: [
      "Fruits & Vegetables",
      "Dairy & Eggs",
      "Bakery",
      "Rice, Atta & Grains",
      "Pulses & Dal",
      "Oil & Ghee",
      "Snacks & Biscuits",
      "Beverages",
      "Spices & Masala",
      "Personal Care",
      "Household & Cleaning",
      "Packaged Food",
    ],
  },
  restaurants: {
    name: "Restaurants",
    categories: [
      "Biryani",
      "Pizza",
      "Burger",
      "Rolls & Wraps",
      "Chinese",
      "Indian",
      "South Indian",
      "Snacks",
      "Sweets & Desserts",
      "Beverages",
      "Thali / Meals",
      "Fast Food",
    ],
  },
  fashion: {
    name: "Fashion",
    categories: [
      "Men - T-Shirts",
      "Men - Shirts",
      "Men - Jeans",
      "Men - Trousers",
      "Men - Ethnic Wear",
      "Women - Sarees",
      "Women - Kurtis",
      "Women - Tops",
      "Women - Dresses",
      "Women - Jeans",
      "Women - Ethnic Wear",
      "Kids",
      "Footwear",
      "Bags",
      "Accessories",
    ],
  },
  medicine: {
    name: "Medicine",
    categories: [
      "Prescription Medicine",
      "OTC Medicine",
      "Vitamins & Supplements",
      "First Aid",
      "Personal Care",
      "Baby Care",
      "Medical Devices",
      "Healthcare Products",
    ],
  },
  electronics: {
    name: "Electronics",
    categories: [
      "Mobiles",
      "Laptops & Computers",
      "Tablets",
      "TVs",
      "Headphones & Earphones",
      "Speakers",
      "Cameras",
      "Smart Watches",
      "Computer Accessories",
      "Mobile Accessories",
      "Home Appliances",
      "Other Electronics",
    ],
  },
  services: {
    name: "Services",
    categories: [
      "Electrician",
      "Plumber",
      "Carpenter",
      "AC Repair",
      "Appliance Repair",
      "Cleaning",
      "Salon & Beauty",
      "Painting",
      "Pest Control",
      "Computer/Mobile Repair",
      "Home Tutor",
      "Other Services",
    ],
  },
};

export const SHOP_TYPE_KEYS = Object.keys(SHOP_CATEGORIES);
